# Generated by Django 3.2 on 2021-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('puzzleid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('fen', models.CharField(max_length=100)),
                ('moves', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('ratingdeviation', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('nbplays', models.IntegerField()),
                ('themes', models.CharField(max_length=255)),
                ('gameurl', models.CharField(max_length=60)),
                ('nbpieces', models.IntegerField()),
                ('nbmoves', models.IntegerField()),
            ],
            options={
                'db_table': 'puzzles',
            },
        ),
    ]
